# Common Application Properties
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  error:
    include-stacktrace: on_param